### ISSUE TITLE
Generation with Jooq 1.16.x fails on missing jakarta.xml.bind.annotation.XmlSchema

### ISSUE THREAD

**Issue by advoretsky** [etiennestuder/gradle-jooq-plugin#207]
I use plugin 
```
id("nu.studer.jooq") version "6.0.1"
```

After upgrade 1.15.7 -> 1.16.1 

```
jooq {
  version.set("1.16.1)
```

generation fails with 

```
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/xml/bind/annotation/XmlSchema
        at org.jooq.util.jaxb.tools.MiniJAXB.getNamespace(MiniJAXB.java:400)
        at org.jooq.util.jaxb.tools.MiniJAXB.addDefaultNamespace(MiniJAXB.java:188)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:175)
        at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:161)
        at org.jooq.codegen.GenerationTool.load(GenerationTool.java:1180)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:203)
Caused by: java.lang.ClassNotFoundException: jakarta.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 6 more```
```
The reason is migration `javax` -> `jakarta` by https://github.com/jOOQ/jOOQ/issues/9641
```
import jakarta.xml.bind.annotation.XmlSchema;
```

**Comment by mrozanc** [comment]
Hello, I made an attempt for a fix here: #208

**Comment by etiennestuder** [comment]
This is fixed in 7.0

**Comment by FrontierPsychiatrist** [comment]
Hey there,
I just tried out to upgrade from 5.0 to 7.0 in my project and still get this error. 

When running the `buildEnvironment` task I see the Jakarta JAR, so I'm a bit lost what to do next.

```
gradle :database:buildEnvironment 
executing gradlew instead of gradle

> Task :database:buildEnvironment

------------------------------------------------------------
Project ':database'
------------------------------------------------------------

classpath
+--- nu.studer.jooq:nu.studer.jooq.gradle.plugin:7.0
|    \--- nu.studer:gradle-jooq-plugin:7.0
|         +--- org.glassfish.jaxb:jaxb-core:3.0.2
|         |    +--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.1
|         |    |    \--- com.sun.activation:jakarta.activation:2.0.1
|         |    +--- com.sun.activation:jakarta.activation:2.0.1
|         |    +--- org.glassfish.jaxb:txw2:3.0.2
|         |    \--- com.sun.istack:istack-commons-runtime:4.0.1
|         +--- org.glassfish.jaxb:jaxb-runtime:3.0.2
|         |    +--- com.sun.activation:jakarta.activation:2.0.1
|         |    \--- org.glassfish.jaxb:jaxb-core:3.0.2 (*)
|         \--- org.jooq:jooq-codegen:3.16.3
|              +--- org.jooq:jooq:3.16.3
|              |    +--- io.r2dbc:r2dbc-spi:0.9.0.RELEASE
|              |    |    \--- org.reactivestreams:reactive-streams:1.0.3
|              |    \--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.0 -> 3.0.1 (*)
|              \--- org.jooq:jooq-meta:3.16.3
|                   \--- org.jooq:jooq:3.16.3 (*)
\--- org.flywaydb.flyway:org.flywaydb.flyway.gradle.plugin:7.12.1
     \--- gradle.plugin.org.flywaydb:gradle-plugin-publishing:7.12.1
          \--- org.flywaydb:flyway-core:7.12.1
```

**Comment by FrontierPsychiatrist** [comment]
Apologies, it was my setup using the Spring BOM for the `jooqGenerator` source set which downgraded the `jakarta.xml.bind-api` dependency to a 2.x version.

For the record I fixed it in my setup like this:

```groovy
// This line was here before
jooqGenerator platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
// Overwrite the Jakarta version for the jOOQ generator source set as it requires a newer version
// than Spring sets
jooqGenerator 'jakarta.xml.bind:jakarta.xml.bind-api:3.0.1' // This line was added
```

**Comment by etiennestuder** [comment]
I've added a [section](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/README.md#enforcing-dependency-versions-via-dependency-rules-from-third-party-plugins-or-from-the-build-itself) to the README should this come up again for someone.
